Modify pre-commit git hook

diff --git a/.githooks/pre-commit b/.githooks/pre-commit
--- a/.githooks/pre-commit
+++ b/.githooks/pre-commit
@@ -1,13 +1,18 @@
-#!/bin/sh
+#!/bin/bash
 
 CMD="npm run build"
 
+#run the prepush command and check the result
 $CMD
+RESULT=$?
+if [ $RESULT -ne 0 ]; then
+	echo "failed $CMD"
+	exit 1
+fi
 
-status=$?
-
-[ $status -eq 0 ] && exit 0 || exit 1
-
-CMD_ADD="git add ."
+CMD_ADD="git add dist/* index.html"
 
 $CMD_ADD
+$CMD_COMMIT
+
+exit 0
